### ISSUE TITLE
🐞: Drop-down slection isn't visible in dark theme.

### ISSUE THREAD

**Issue by joe733** [duckduckgo/duckduckgo-styles#62]
| Dark Theme | Light Theme |
| --- | --- |
| ![image](https://user-images.githubusercontent.com/38415384/103144703-f8629500-4753-11eb-8993-318f1eef2d94.png) | ![Screenshot from 2020-12-26 08-21-00](https://user-images.githubusercontent.com/38415384/103144731-76bf3700-4754-11eb-811a-157a9ccb3cc0.png) |

The `Analogous` selection in the drop-down menu, right below the `Settings`, under the search icon 🔍, isn't properly visible in dark theme.

**Comment by joe733** [comment]
Not sure if this is the right place to open this issue, but I guess collaborator can move them to a different repository.

**Comment by moollaza** [comment]
Thanks for reporting @joe733. This isn't the correct repo (the theme CSS is actually closed source), but after testing on different browsers, it seems like this might be a browser/OS bug on your side?

I checked Firefox, Chrome, and Safari on my Mac and across all 3, the dropdown remains unstyled in both themes. So even in the dark theme the dropdown has a white background.

It looks like you're on Ubuntu? I'd suggest you check other browsers to see if it's happening across all of them or just yours.

I'm going to close as the issues isn't relevant to this code, but if you can confirm the bug is with our theme styles I'll open an internal issue.

**Comment by joe733** [comment]
@moollaza thanks for the reply. I check for these three:

![Group 3](https://user-images.githubusercontent.com/38415384/105949085-24926e00-6092-11eb-830b-5c3f891bb693.png)

I guess you're right, it could be a browser issue, not sure though.
